New base64 command
briandfoy/PerlPowerTools pull request #144
Opened 2023-03-21 15:43 UTC by mknos

Justification:
* MIME::Base64 is included as part of perl
* NetBSD now has a base64 command, with arguments similar to GNU version

Notes:
* Output file option (-o) is what I'm used to doing when running b64decode on OpenBSD so it's supported in this version
* NetBSD version supports multiple input files but this version follows GNU behaviour and raises an error

2023-03-21 21:29 UTC, briandfoy requested changes
This looks good and I have a few minor comments.

2023-03-31 05:24 UTC, briandfoy commented
@mknos If you can resolve the minor questions, I can merge this command.

2023-04-01 14:18 UTC, mknos commented on bin/base64
> +getopts('do:', \%opt) or usage();
I'm a little against --long-options but I've added -v for version (as supported by gnu tools such as gcc and as)

2023-04-01 19:29 UTC, briandfoy approved these changes
Thanks,

2023-04-01 19:30 UTC, merged