rm: exit code 1 on error
briandfoy/PerlPowerTools pull request #200
Opened 2023-07-11 14:46 UTC by mknos

* Exit code 1 indicates an error occurred when processing one or more arguments
* An error processing one argument doesn't prevent the next argument from processing
* Flag error (printing $! if appropriate) for these cases:
1) expected file, got directory
2) rmdir() failed on a directory (in -r mode)
3) opendir() failed (in -r mode), e.g. permission denied
4) unlink() failed, e.g. file does not exist
5) expected an argument, got zero

* closedir() isn't needed if opendir() failed
* While here remove -P flag for "wiping" a file
1) not part of standard rm command
2) implementation assumes writing over a file in place will effectively wipe content on disk
3) implementation assumes the file being wiped can fit in memory (creates a string the same size as file)
4) physical destruction is *always* better

2023-07-11 15:32 UTC, briandfoy commented
I see this, but give me a couple days to look through it since this one is a bit more involved than the other PRs you've had.

2023-07-12 02:47 UTC, briandfoy commented
I agree on `-P`, but maybe we should just make it a no-op instead of removing it. On macOS:

```
-P      This flag has no effect.  It is kept only for backwards
             compatibility with 4.4BSD-Lite2.
```

2023-07-12 02:53 UTC, briandfoy requested changes

2023-07-12 02:53 UTC, briandfoy commented on bin/rm
> -use vars qw( $opt_i $opt_f $opt_r $opt_R $opt_P );
Let's make $opt_P a no-op instead. Maybe issue a warning.

2023-07-12 02:53 UTC, briandfoy commented on bin/rm
> +my $Err = 0;
Maybe the return value of processFile should decide if something gets added to $Err? I'd rather have that then subroutines accessing variables outside their scope.

2023-07-12 02:53 UTC, briandfoy commented on bin/rm
> -{
I'd turn overWriteFile into a warning and a return.

2023-07-12 02:57 UTC, briandfoy commented
So, on alpine linux, I get exit of 1 with no arguments, but on macOS and freebsd I get 64. This is not a big deal.

I recently made https://github.com/briandfoy/PerlPowerTools/blob/master/PROGRAMMING_STYLE.md , which has a few things to say about exit values. You don't need to do all that stuff for this PR, but I'd gradually like to move things toward modulinos and a common structure among programs.

2023-07-12 06:16 UTC, mknos commented
* NetBSD, OpenBSD, FreeBSD (I think Mac follows this), HP-UX  manuals are consistent: exit code >0 means error
* This patch doesn't distinguish how many arguments failed to process, or the processing error that occurred; exit code 1 is used for everything
* This could be changed later but this patch is at least compliant with standard

2023-07-12 22:19 UTC, briandfoy approved these changes

2023-07-12 22:19 UTC, merged

2023-07-12 22:20 UTC, briandfoy commented
I merged this, but I'm going to add additional changes. I started working on this program and it got a bit out of hand as I fixed the -i and -f issue.

Thanks,