ls: retire invalid ioctl()
briandfoy/PerlPowerTools pull request #301
Opened 2023-10-22 11:40 UTC by mknos

* The ioctl number assumed for TIOCGWINSZ is non-portable and would only work by accident
* The ioctl() call fails on my system because it is invalid
* Perl Cookbook example has the exact hex constant and mentions it is not portable [1]
* It seems better to remove this construct until it can be replaced with something that works

1. https://www.oreilly.com/library/view/perl-cookbook/1565922433/ch04s19.html

2023-10-23 00:36 UTC, briandfoy commented
Yeah, we should fix this. This patch is better than what is already happening.

However, is hard-coding 80 the way to go? Is there another way to get the terminal width in windows that works across different console applications? Maybe https://stackoverflow.com/questions/6812224/getting-terminal-size-in-c-for-windows is useful? Is that in Win32:: somewhere? stty maybe? Use Terminal::ReadKey if it is around?

If you don't want to deal with all that in this patch, that is fine, but we can open an issue for it otherwise.

2023-10-24 05:55 UTC, briandfoy requested changes

2023-10-24 05:55 UTC, briandfoy commented on bin/ls
> +my $WinCols = 80;	# window columns of output
Is there a way we can query the terminal and still  use this as a fallback?

2023-10-24 17:42 UTC, briandfoy commented
I marked this as "changes requested", but if you don't want to add another solution with this patch that's fine. We can definitely remove the broken method. I'd prefer another solution, but baby steps is fine. If you don't want to do that just yet, just say so and I'll merge this.

2023-10-26 02:03 UTC, mknos commented
I added a new commit. According to the documentation, CPAN module IO::Tty has been tested on many different unix systems. get_winsize() returns a sane result on my Linux system. I suspect it doesn't work out of the box on Windows; however, the old ioctl() code didn't work there either. Possibly we can add some windows-specific code in the get_columns() wrapper later.

2023-10-26 04:27 UTC, briandfoy requested changes

2023-10-26 04:27 UTC, briandfoy commented on bin/ls
> +    require IO::Tty;
IO::Tty doesn't work on Windows, and on linux and friends I think it's too much. Here are some things that will get the columns:

    stty size  | cut -d' ' -f 2

    tput cols

On Windows with powershell (with Perl post processing):

    powershell -command "&{(get-host).ui.rawui.WindowSize;}"

2023-11-14 08:23 UTC, briandfoy commented
I'll merge this and fix it up later.

2023-11-14 08:23 UTC, merged

2023-11-14 08:37 UTC, briandfoy commented
This is fixed by 7ee2d98a20aff9a4b644c8ff5eb455421e7dacb6.