od: support multiple input files
briandfoy/PerlPowerTools pull request #463
Opened 2024-02-15 03:11 UTC by mknos

* Standards document specifies multiple input files should be processed [1]
* Follow BSD od and read stdin only if no arguments are given
* Update usage string
* Options -N and -j affect the input stream overall, not just the 1st file processed
* Uneven input data left over at EOF is combined with input from the next file
* Uneven input data at end of the last file gets its own dump_line() call
* Formatting routines are now written without the need for global $pffmt
* test1: "echo hello |  perl od -c -N 2" --> format 1st two bytes from stdin as characters
* test2: "od -j 1 -x  awk ar" --> dump awk and ar files as hex, skipping 1st byte of input

1. https://pubs.opengroup.org/onlinepubs/009696899/utilities/od.html

2024-02-15 05:11 UTC, briandfoy commented
`od` has some tests to update to support this change.

2024-02-19 02:58 UTC, mknos commented
Sorry about that. I had a look, and the final emit_offset() call was printing a space after the offset, followed by a newline.
Technically the space is not required, only the newline is.

2024-02-29 04:09 UTC, briandfoy commented
I see this but I'm too tired this week to understand that change. Give me a couple days to look at it.

2024-02-29 21:54 UTC, briandfoy requested changes
I think this is good, but it's a big enough change that I think you should add yourself as an author.

2024-03-03 05:49 UTC, briandfoy approved these changes

2024-03-03 05:54 UTC, merged

2024-03-03 08:25 UTC, briandfoy commented
changes: support multiple input files