bc: regression on old perl
briandfoy/PerlPowerTools pull request #511
Opened 2024-03-20 08:44 UTC by mknos

* The default mode of this bc is not bc at all because it is not arbitrary precision; numbers are just perl floating point values
* It's still useful enough as a basic calculator, but not as a bc-compatible one
* For fun I booted DamnSmallLinux live-cd v4.4.10
* The version of perl on this old linux doesn't include Math::BigFloat
* bc would not load, even in default mode because of a "use" statement; lazy-load with "require" avoids the error
* test1: "perl bc" --> load in not-arbitrary-precision mode and 2**128/33333 is a perl floating point number
* test2: "perl bc -b" --> fail to load Math::BigFloat on old perl

2024-03-20 12:59 UTC, briandfoy commented
Huh, that's strange since Math::BigInt is part of the core library since Perl 5.

2024-03-20 13:00 UTC, briandfoy requested changes
Let's catch failures in the require too.

2024-03-21 00:32 UTC, mknos commented
> Huh, that's strange since Math::BigFloat is part of the core library since Perl 5.

I had a feeling stuff had been forcibly deleted from the perl distro on damnsmalllinux 4.4.10 to make the live-cd ISO 50 MB. I just downloaded perl-5.8.0 sources and confirmed that it contains Math::BigFloat version 1.35. The lazy-load patch is still ok but I can add a commit to print a nicer error if Math::BigFloat isn't there.

2024-03-21 06:17 UTC, briandfoy commented
That sounds like a good plan. Do that.

2024-03-23 16:33 UTC, briandfoy approved these changes

2024-03-23 16:33 UTC, merged

2024-03-23 16:34 UTC, briandfoy commented
changes: handle cases where Math::Big* is missing (like minimal distros of perl)