shar: handle filename with space
briandfoy/PerlPowerTools pull request #565
Opened 2024-04-17 12:11 UTC by mknos

* shar from GNU sharutils can work with a filename with spaces, but this version can't
* Address this by quoting the filename passed to mkdir and sed
* It's not harmful to quote files which don't have a space
* While here, print an error if close() failed

```
%perl shar '0 1' > new.shar
%sh new.shar
x - 0 1
sed: can't read 1: No such file or directory
```

2024-04-17 23:21 UTC, briandfoy requested changes
Can we fix up the problem of the filename having the quote character as a literal character? That would have already been a problem, but now that we're here maybe we can handle that.

2024-04-17 23:21 UTC, briandfoy commented on bin/shar
> +	print "mkdir -p '$f'\n";
what is the filename has a ' in it though?

2024-04-18 12:05 UTC, mknos commented
Being paranoid here is good. I committed a version that now works with filenames containing a quote.

2024-04-18 13:41 UTC, briandfoy approved these changes

2024-04-18 13:41 UTC, merged