ed: allow repeated search with // and ??
briandfoy/PerlPowerTools pull request #768
Opened 2024-10-23 06:16 UTC by mknos

* In commit 78d54294099cfab729e156e8a0f123939da14179, repeat search was only implemented for "/" and "?"
* Add support for empty patterns specified as "??" and "//" (these may be followed by whitespace, but single "?" and "/" may not)
* test1: "/\n" --> repeat search down
* test2: "/ \n" --> start new search (down) for " "
* test3: "// \n" --> repeat search down
* test4: "?\n" --> repeat search up
* test5: "? \n"--> start new search (up) for " "
* test6: "?? \n --> repeat search up
* Entering //n doesn't seem to work for repeating search then issuing n command (this could be supported later)

2024-10-23 17:35 UTC, briandfoy requested changes
Maybe it's time to add these to the docs under editor commands.

2024-10-24 01:13 UTC, mknos commented
Thanks for the reminder. I added a commit to document the search features, including global (g) command which doesn't support modifying the buffer at this time.

2024-10-24 03:06 UTC, briandfoy approved these changes

2024-10-24 03:06 UTC, merged

2024-10-24 03:07 UTC, briandfoy commented
changes: allow repeated search with // and ??